/*
 * SPI.c
 *
 *  Created on: Aug 18, 2024
 *      Author: markk
 */


#include "SPI.h"
#include "GPIO/GPIO.h"


void SPI_InitMaster(void){

	GPIO_SetPinDirection(SPI_PORT,SPI_MOSI_PIN,GPIO_OUTPUT); /*MOSI*/
	GPIO_SetPinDirection(SPI_PORT,SPI_MISO_PIN,GPIO_INPUT); /*MISO*/
	GPIO_SetPinDirection(SPI_PORT,SPI_SCK_PIN,GPIO_OUTPUT); /*SCK*/
	GPIO_SetPinDirection(SPI_PORT,SPI_SS_PIN,GPIO_OUTPUT); /*SS*/

	SET_BIT(SPCR , SPCR_MSTR);
	CLEAR_BIT(SPCR , SPCR_DORD);
	CLEAR_BIT(SPCR , SPCR_CPOL);
	CLEAR_BIT(SPCR , SPCR_CPHA);

#if SPI_SCK_SEL == DIV_FACTOR_4
	CLEAR_BIT(SPCR , SPCR_SPR0);
	CLEAR_BIT(SPCR , SPCR_SPR1);
	CLEAR_BIT(SPCR , SPSR_SPI2X);
#elif SPI_SCK_SEL == DIV_FACTOR_16
	SET_BIT(SPCR , SPCR_SPR0);
	CLEAR_BIT(SPCR , SPCR_SPR1);
	CLEAR_BIT(SPCR , SPSR_SPI2X);
#elif SPI_SCK_SEL == DIV_FACTOR_64
	CLEAR_BIT(SPCR , SPCR_SPR0);
	SET_BIT(SPCR , SPCR_SPR1);
	CLEAR_BIT(SPCR , SPSR_SPI2X);
#elif SPI_SCK_SEL == DIV_FACTOR_128
	SET_BIT(SPCR , SPCR_SPR0);
	SET_BIT(SPCR , SPCR_SPR1);
	CLEAR_BIT(SPCR , SPSR_SPI2X);
#elif SPI_SCK_SEL == DIV_FACTOR_2X_2
	CLEAR_BIT(SPCR , SPCR_SPR0);
	CLEAR_BIT(SPCR , SPCR_SPR1);
	SET_BIT(SPCR , SPSR_SPI2X);
#elif SPI_SCK_SEL == DIV_FACTOR_2X_8
	SET_BIT(SPCR , SPCR_SPR0);
	CLEAR_BIT(SPCR , SPCR_SPR1);
	SET_BIT(SPCR , SPSR_SPI2X);
#elif SPI_SCK_SEL == DIV_FACTOR_2X_32
	CLEAR_BIT(SPCR , SPCR_SPR0);
	SET_BIT(SPCR , SPCR_SPR1);
	SET_BIT(SPCR , SPSR_SPI2X);
#elif SPI_SCK_SEL == DIV_FACTOR_2X_64
	SET_BIT(SPCR , SPCR_SPR0);
	SET_BIT(SPCR , SPCR_SPR1);
	SET_BIT(SPCR , SPSR_SPI2X);
#endif
	//spi enable
	SET_BIT(SPCR , SPCR_SPE);
}
void SPI_InitSlave(void){


	GPIO_SetPinDirection(SPI_PORT,SPI_MOSI_PIN,GPIO_OUTPUT); /*MOSI*/
	GPIO_SetPinDirection(SPI_PORT,SPI_MISO_PIN,GPIO_INPUT); /*MISO*/
	GPIO_SetPinDirection(SPI_PORT,SPI_SCK_PIN,GPIO_OUTPUT); /*SCK*/
	GPIO_SetPinDirection(SPI_PORT,SPI_SS_PIN,GPIO_OUTPUT); /*SS*/

	CLEAR_BIT(SPCR , SPCR_MSTR);
	CLEAR_BIT(SPCR , SPCR_DORD);
	CLEAR_BIT(SPCR , SPCR_CPOL);
	CLEAR_BIT(SPCR , SPCR_CPHA);

#if SPI_SCK_SEL == DIV_FACTOR_4
	CLEAR_BIT(SPCR , SPCR_SPR0);
	CLEAR_BIT(SPCR , SPCR_SPR1);
	CLEAR_BIT(SPCR , SPSR_SPI2X);
#elif SPI_SCK_SEL == DIV_FACTOR_16
	SET_BIT(SPCR , SPCR_SPR0);
	CLEAR_BIT(SPCR , SPCR_SPR1);
	CLEAR_BIT(SPCR , SPSR_SPI2X);
#elif SPI_SCK_SEL == DIV_FACTOR_64
	CLEAR_BIT(SPCR , SPCR_SPR0);
	SET_BIT(SPCR , SPCR_SPR1);
	CLEAR_BIT(SPCR , SPSR_SPI2X);
#elif SPI_SCK_SEL == DIV_FACTOR_128
	SET_BIT(SPCR , SPCR_SPR0);
	SET_BIT(SPCR , SPCR_SPR1);
	CLEAR_BIT(SPCR , SPSR_SPI2X);
#elif SPI_SCK_SEL == DIV_FACTOR_2X_2
	CLEAR_BIT(SPCR , SPCR_SPR0);
	CLEAR_BIT(SPCR , SPCR_SPR1);
	SET_BIT(SPCR , SPSR_SPI2X);
#elif SPI_SCK_SEL == DIV_FACTOR_2X_8
	SET_BIT(SPCR , SPCR_SPR0);
	CLEAR_BIT(SPCR , SPCR_SPR1);
	SET_BIT(SPCR , SPSR_SPI2X);
#elif SPI_SCK_SEL == DIV_FACTOR_2X_32
	CLEAR_BIT(SPCR , SPCR_SPR0);
	SET_BIT(SPCR , SPCR_SPR1);
	SET_BIT(SPCR , SPSR_SPI2X);
#elif SPI_SCK_SEL == DIV_FACTOR_2X_64
	SET_BIT(SPCR , SPCR_SPR0);
	SET_BIT(SPCR , SPCR_SPR1);
	SET_BIT(SPCR , SPSR_SPI2X);
#endif
	//spi enable
	SET_BIT(SPCR , SPCR_SPE);


}
void SPI_EnableSS(void){

}
void SPI_DisableSS(void){

}
void SPI_TransferByte(u8 data){
	SPDR = data;
	while(!(SPSR & (1<<SPSR_SPIF)));

}
u8 SPI_ReceiveByte(void){
	while(!(SPSR & (1<<SPSR_SPIF)));	/* Wait till reception complete */
	return(SPDR);			/* Return received data */

}

void SPI_SendString(u8 * u8String)
{
	while((*u8String) != 0)
	{
		SPI_TransferByte(*u8String);
		u8String++;
	}
}
void SPI_EnableInterrupt(void);
void SPI_DisableInterrupt(void);
